security:
    encoders:
        Beachteam\BeachteamBundle\Entity\User:
            algorithm: bcrypt
            cost: 15

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        users:
          entity:
              class: BeachteamBundle:User
              property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: beachteam_loginpage
                check_path: beachteam_logincheck
                username_parameter: login[username]
                password_parameter: login[password]
                always_use_default_target_path: true
                default_target_path: BeachteamBundle_adminpage
            logout:
                path:   beachteam_logout
                target: beachteam_loginpage
            remember_me:
                 key:      "%secret%"
                 lifetime: 31536000 # 365 days in seconds
                 path:     /
                 domain:   ~ # Defaults to the current domain from $_SERVER
                 remember_me_parameter: remember

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
