# HOMEPAGE (ONE PAGE WEBSITE)
BeachteamBundle_homepage:
    pattern:  /
    defaults: { _controller: BeachteamBundle:Default:index }
    requirements:
        _method:  GET|POST

# BACKOFFICE
BeachteamBundle_loginpage:
    pattern:  /admin/login
    defaults: { _controller: BeachteamBundle:Admin:login }
    requirements:
        _method:  GET|POST

BeachteamBundle_adminpage:
    pattern:  /admin/index
    defaults: { _controller: BeachteamBundle:Admin:index }

BeachteamBundle_adminbiopage:
    pattern:  /admin/bio
    defaults: { _controller: BeachteamBundle:Admin:bio }

BeachteamBundle_admintournamentspage:
    pattern:  /admin/tournaments
    defaults: { _controller: BeachteamBundle:Admin:tournaments }

BeachteamBundle_adminarticlespage:
    pattern:  /admin/articles
    defaults: { _controller: BeachteamBundle:Admin:articles }

BeachteamBundle_adminpicturespage:
    pattern:  /admin/pictures
    defaults: { _controller: BeachteamBundle:Admin:pictures }

BeachteamBundle_adminsponsorspage:
    pattern:  /admin/sponsors
    defaults: { _controller: BeachteamBundle:Admin:sponsors }


